name: Demand Request
description: Raise a demand before you can order something
title: "[Demand]: raised for "
labels: [demand, new]
assignees:
- PavlenkoKate
body:
- type: checkboxes
  id: type
  attributes:
    label: Is it a production of new item or a repair of existing one?
    options:
    - label: Production
    - label: Repair
  validations:
    required: true
- type: checkboxes
  id: activity
  attributes:
    label: From whom shall we source it?
    options:
    - label: 3rd party
    - label: Internal manufacturing
  validations:
    required: true
- type: input
  id: vendors
  attributes:
    label: Provide a list of potential providers
  validations:
    required: false
- type: input
  id: quantity
  attributes:
    label: Provide required number of items
  validations:
    required: false
- type: input
  id: delivery
  attributes:
    label: Provide expected delivery date
  validations:
    required: false
- type: input
  id: file
  attributes:
    label: Please provide a link to step file or technical drawing
  validations:
    required: false
